apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dsapp
  namespace: default
  labels:
    app: dsapp
spec:
  selector:
    matchLabels:
      app: dsapp
  template:
    metadata:
      labels:
        app: dsapp
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: dsapp
        image: ubuntu:latest
        command:
          - sleep
          - "3600"
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      terminationGracePeriodSeconds: 30
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai