apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app.kubernetes.io/name: webapp
    apptype: webapp
spec:
  containers:
  - name: webapp
    image: httpd:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: webapp-svc
spec:
  selector:
    apptype: webapp
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80