apiVersion: v1
kind: Pod
metadata:
  name: villa
  labels:
    app.kubernetes.io/name: villa
    app: villa
spec:
  containers:
  - name: villa
    image: prateekkumawat/kube11:web1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: villa-svc 
spec:
  selector:
    app: villa
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80