apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-wordpress
  namespace: wordpress
  labels:
    app: wordpress-app
    apptype: wpapp
spec:
  selector:
    matchLabels:
      app: wordpress-app
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - name: wp-wordpress
        image: wordpress:latest
        resources:
          requests: 
             memory: "500Mi"
             cpu: "400m"
          limits:
            memory: "1000Mi"
            cpu: "800m"
        ports:
        - containerPort: 80
        env: 
        - name: WORDPRESS_DB_USER
          valueFrom: 
            secretKeyRef:
              key: user
              name: admin-app-secret
        - name: WORDPRESS_DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              key: password
              name: admin-app-secret
        - name: WORDPRESS_DB_NAME
          valueFrom: 
            secretKeyRef:
              key: dbdata
              name: admin-info
        - name: WORDPRESS_DB_HOST
          value: wp-mysql-svc.wordpress.svc.cluster.local
        volumeMounts:
        - name: wp-data-mount
          mountPath: /var/www/html
      volumes:
      - name: wp-data-mount
        mountPath: wpapp-data-vol0

---
apiVersion: v1
kind: Service
metadata:
  name: wp-wordpress-svc
  namespace: wordpress
spec:
  selector:
    app: wordpress-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
