apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-developer
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "deployments", "replicasets", "daemonset", "services"]
  verbs: ["get", "watch", "list", "create", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-bind-developer
  namespace: default
subjects:
- kind: User
  name: prateek
  apiGroup: ""
roleRef:
  kind: ClusterRole 
  name: role-developer 
  apiGroup: ""