apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-taint-toleration-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: pods_seclector_basis_app
                operator: In
                values:
                - mgmt
          - weight: 50
            preference:
              matchExpressions:
              - key: pods_seclector_basis_app
                operator: In
                values:
                - webapp           
      containers:
      - name: affinity-taint-toleration-deployment
        image: nginx:latest
        resources:
          limits:
            memory: "200Mi"
            cpu: "300m"
        ports:
        - containerPort: 80